name: Update Snapshots

on:
  workflow_dispatch:

jobs:
  update_snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on main"
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Setup E2E Environment
        uses: ./.github/actions/setup-e2e-env

      - name: Install Templates Dependencies
        run: ./scripts/install-deps

      - name: Run emulator
        run: |
          set -e
          juno dev start --headless &
          juno dev wait
          juno login --emulator --mode development --headless
          juno config --mode development --headless

      - name: Run tests and update Snapshots
        run: ./scripts/e2e e2e:ci:snapshots

      - name: Commit Playwright updated snapshots
        uses: EndBug/add-and-commit@v9
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add: e2e
          default_author: github_actions
          message: 'ðŸ¤– update snapshots'
